Repository kubeflow/fate-operator, pull requests merged in 2020-07, with the labels that each got.

#8 Add Make target for non-developer
  Makefile
  README.md
Labels: approved, lgtm, size/S

#9 chore: Change the binary name
  .gitignore
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S

#16 feat: support deploymet with images in private repository
  api/v1beta1/kubefate_types.go
  config/crd/bases/app.kubefate.net_kubefates.yaml
  config/samples/app_v1beta1_kubefate.yaml
  controllers/fatecluster_controller_test.go
  controllers/fatejob_controller_test.go
  controllers/kubefate_controller.go
  controllers/kubefate_controller_test.go
Labels: approved, lgtm, size/S

#18 feat: Replace the environment variable with the CLI parameter
  controllers/fatecluster_controller.go
  controllers/fatecluster_controller_test.go
  controllers/fatejob_controller_test.go
  main.go
Labels: approved, lgtm, size/S

#17 feat: Use ObjectReference and supporting FateClusters in other namespaces
  api/v1beta1/fatejob_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/app.kubefate.net_fatejobs.yaml
  config/samples/app_v1beta1_fatejob.yaml
  controllers/fatejob_controller.go
  controllers/fatejob_controller_test.go
Labels: approved, lgtm, size/M

#22 feat: Kubefate's database Mongo supports persistence
  api/v1beta1/kubefate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/app.kubefate.net_kubefates.yaml
  config/samples/app_v1beta1_kubefate.yaml
  controllers/fatejob_controller.go
  controllers/fatejob_controller_test.go
  controllers/kubefate_controller.go
Labels: approved, lgtm, size/XXL
