Repository kubeflow/fate-operator, pull requests merged in 2020-06, with the labels that each got.

#1 Add LaynePeng as fate-operator project owner.
  OWNERS
Labels: approved, lgtm

#3 Add readme file to introduce the project.
  README.md
  doc/diagrams/fate-operator-1.png
  doc/diagrams/fate-operator-2.png
  doc/diagrams/fate-operator-3.png
  doc/diagrams/fate-operator-fl.png
  doc/diagrams/fate-operator-overall.png
Labels: approved, lgtm, size/S

#4 Add Jiahaoc as the project OWNER
  OWNERS
Labels: approved, lgtm, size/XS
